#!/bin/sh -e

repo_main=http://ftp.us.debian.org/debian/pool/main


startup() {
    mkdir -p /proc /sys /tmp
    mount /proc
    mount /sys
    mount -t tmpfs none /tmp
    mount -n -o mode=0755 -t devtmpfs devtmpfs /dev
    mkdir -p /dev/pts
    mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts
    depmod -a

    [ ! -e /etc/mtab ] && ln -s /proc/mounts /etc/mtab

    mkdir -p /var/lib/dpkg
    [ ! -e /var/lib/dpkg/status ] && ( echo > /var/lib/dpkg/status )

    [ -e /lib/modules/4.19.0-9-amd64/kernel/drivers/ata ] && hdgo

    if [ -e /bin/bash ]
        then exec /bin/bash
        else exec /bin/sh
    fi
}


net() {
    modprobe e1000
    ip link set eth0 up
    udhcpc
}


hd() {
    if [ ! -e /lib/modules/4.19.0-9-amd64/kernel/drivers/ata ] ; then
    cd /tmp

    repo=$repo_main/l/linux-signed-amd64
    wget $repo/ata-modules-4.19.0-9-amd64-di_4.19.118-2_amd64.udeb
    wget $repo/sata-modules-4.19.0-9-amd64-di_4.19.118-2_amd64.udeb
    wget $repo/crc-modules-4.19.0-9-amd64-di_4.19.118-2_amd64.udeb
    wget $repo/ext4-modules-4.19.0-9-amd64-di_4.19.118-2_amd64.udeb

    udpkg -i ata-modules-4.19.0-9-amd64-di_4.19.118-2_amd64.udeb  \
             sata-modules-4.19.0-9-amd64-di_4.19.118-2_amd64.udeb \
             crc-modules-4.19.0-9-amd64-di_4.19.118-2_amd64.udeb  \
             ext4-modules-4.19.0-9-amd64-di_4.19.118-2_amd64.udeb

    depmod -a
    fi

    modprobe ata_piix
    modprobe sd_mod
    modprobe crc32c_generic
    modprobe ext4

    mkdir -p /mnt
    if [ -e /dev/sda1 ]; then
      mount /dev/sda1 /mnt
    fi
}

hdgo() {
    hd && exec chroot /mnt busybox init
}

mkfs() {
    cd /tmp

    wget $repo_main/g/glibc/libc6-udeb_2.28-10_amd64.udeb

    repo=$repo_main/u/util-linux
    wget $repo/libblkid1-udeb_2.33.1-0.1_amd64.udeb
    wget $repo/libuuid1-udeb_2.33.1-0.1_amd64.udeb
    wget $repo/fdisk-udeb_2.33.1-0.1_amd64.udeb

    wget $repo_main/e/e2fsprogs/e2fsprogs-udeb_1.44.5-1+deb10u3_amd64.udeb
    
    udpkg -i libc6-udeb_2.28-10_amd64.udeb         \
             libblkid1-udeb_2.33.1-0.1_amd64.udeb  \
             libuuid1-udeb_2.33.1-0.1_amd64.udeb   \
             fdisk-udeb_2.33.1-0.1_amd64.udeb      \
             e2fsprogs-udeb_1.44.5-1+deb10u3_amd64.udeb

    echo -e 'o\nn\n\n\n\n\na\nw' | fdisk /dev/sda
    mkfs.ext2 /dev/sda1

    mkdir -p /mnt
    mount /dev/sda1 /mnt
}


boot() {
    cd /tmp
    
    [ ! -e libc6-udeb_2.28-10_amd64.udeb ] && \
    wget $repo_main/g/glibc/libc6-udeb_2.28-10_amd64.udeb
    
    repo=$repo_main/s/syslinux
    wget $repo/syslinux-common_6.04~git20190206.bf6db5b4+dfsg1-1_all.deb
    wget $repo/extlinux_6.04~git20190206.bf6db5b4+dfsg1-1_amd64.deb

    udpkg -i libc6-udeb_2.28-10_amd64.udeb  \
             syslinux-common_6.04~git20190206.bf6db5b4+dfsg1-1_all.deb \
             extlinux_6.04~git20190206.bf6db5b4+dfsg1-1_amd64.deb

    mkdir -p /mnt/boot
    extlinux -i /mnt/boot
    cat /usr/lib/EXTLINUX/mbr.bin > /dev/sda

    tar xf /boot.tar -C /mnt
    cp /init /mnt/
    sync
}


slim() {
    tar xf /debian-slim.tar -C /mnt

    cp /bin/busybox /mnt/bin/
    for a in depmod modprobe insmod lsmod ip udhcpc wget; do 
        ln -s busybox /mnt/bin/$a
    done
    cp -r /etc/fstab /etc/udhcpc /mnt/etc/
    sync
}


vga() {
    modprobe virtio_pci
    modprobe virtio_gpu
    modprobe psmouse
    modprobe evdev
}

# Create a rootfs from scratch
install() {
    /init net
    /init hd
    /init mkfs
    /init boot
    /init slim
}


case "$1" in
net)      net ;;
hd)       hd ;;
hdgo)     hdgo ;;
mkfs)     mkfs ;;
boot)     boot ;;
slim)     slim ;;
vga)      vga ;;
install)  install ;;
*)        startup ;;
esac
